defaults:
  - train: train-default
  - model: unet-mnist
  - sde: vp-sde
  - optimizer: adamw
  - data: mnist
  - logger: wandb
  - hydra: hydra-default
  - _self_

name: 'vp-sde_mnist'
device: 'cuda:1'
ckpt_path: ${hydra:run.dir}/ckpts/${name}.ckpt